name: storyboard
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  storybook_flutter: ^0.5.0
  iupp_components:
    path:
      ../../iupp-components

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IuppIcons
      fonts:
        - asset: assets/fonts/IuppIcons.ttf
        - asset: assets/fonts/IuppIcons.woff
