name: iupp_components
description: Collection of components to be used on the Iupp project
version: 0.0.1
author:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0-nullsafety.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail_image_network: ^0.1.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: IuppIcons
      fonts:
        - asset: assets/fonts/IuppIcons.ttf
        - asset: assets/fonts/IuppIcons.woff
