name: iupp_components
description: Collection of components to be used on the Iupp project
version: 0.0.1
publish_to: none
author:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  iupp_core:
    path: ../iupp_core

  carousel_slider: ^4.0.0-nullsafety.0

dev_dependencies:
  faker: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail_image_network: ^0.1.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: IuppIcons
      fonts:
        - asset: lib/fonts/IuppIcons.ttf
        - asset: lib/fonts/IuppIcons.woff
    - family: ItauDisplay
      fonts:
        - asset: lib/fonts/ItauDisplay_Bd.ttf
        - asset: lib/fonts/ItauDisplay_Blk.ttf
        - asset: lib/fonts/ItauDisplay_He.ttf
        - asset: lib/fonts/ItauDisplay_Lt.ttf
        - asset: lib/fonts/ItauDisplay_Rg.ttf
        - asset: lib/fonts/ItauDisplay_XBd.ttf
