name: iupp_marketplace_buyer
description: A new flutter module project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  iupp_core:
    path: ../iupp_core
  iupp_components:
    path: ../iupp-components

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  faker: ^2.0.0-rc.2
  mocktail: ^0.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: IuppIcons
      fonts:
        - asset: packages/iupp_components/fonts/IuppIcons.ttf
        - asset: packages/iupp_components/fonts/IuppIcons.woff
    - family: ItauDisplay
      fonts:
        - asset: packages/iupp_components/fonts/ItauDisplay_Bd.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_Blk.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_He.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_Lt.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_Rg.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_XBd.ttf
  module:
    androidX: true
    androidPackage: com.example.iupp_marketplace_buyer
    iosBundleIdentifier: com.example.iuppMarketplaceBuyer
