name: iupp_onboarding
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: IuppIcons
      fonts:
        - asset: packages/iupp_components/fonts/IuppIcons.ttf
        - asset: packages/iupp_components/fonts/IuppIcons.woff
    - family: ItauDisplay
      fonts:
        - asset: packages/iupp_components/fonts/ItauDisplay_Bd.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_Blk.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_He.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_Lt.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_Rg.ttf
        - asset: packages/iupp_components/fonts/ItauDisplay_XBd.ttf

  module:
    androidX: true
    androidPackage: com.example.iupp_onboarding
    iosBundleIdentifier: com.example.iuppOnboarding
